### PR TITLE
Fix compiler deprecation warnings

### PR DESCRIPTION
**Pull request by carun**

### CODE REVIEW

**Comment by kyllingstad** [comment]
`&arr[0]` is generally not a valid replacement for `arr.ptr`, because `arr` may be empty. This is why the unittests are currently failing.

What is the reason for this pull request, anyway? I cannot find any mention of `.ptr` being deprecated anywhere.

**Comment by kyllingstad** [comment]
Ok, I just downloaded the latest DMD version, and now I see the warnings too. I think the correct solution here is to add a new function,

    T* ptr(T)(T[] arr) { return arr.empty ? null : &arr[0]; }

and then replace `a.ptr` with `ptr(a)` everywhere.

**Comment by carun** [comment]
OK, I just did a

```
git reset HEAD^ --hard && git push -f origin master
```
to implement the new change and I find that the PR got closed. Coming from hg isn't easy to deal with git.

**Comment by carun** [comment]
Also, writing a custom function `ptr(a)` may not be elegant, as the compiler should be able to infer it for us. What do you think?

After all `&a[0]` will be null if a.length is 0. Or better to use
```
T* ptr(T)(T[] arr) { return arr.length == 0 ? null : &arr[0]; }
```

**Comment by kyllingstad** [comment]
Thanks!

**Comment by kyllingstad** [comment]
> Also, writing a custom function `ptr(a)` may not be elegant, as the compiler should be able to infer it for us. What do you think?
>
> After all `&a[0]` will be null if a.length is 0.

No, then `&a[0]` is undefined, because there is no zeroth element to take the address of.

**Comment by carun** [comment]
> No, then &a[0] is undefined, because there is no zeroth element to take the address of.

I see. If that's true, is it not error on the part of the compiler to give the below warning?

```
src/zmqd.d(462,40): Deprecation: data.ptr cannot be used in @safe code, use &data[0] instead
src/zmqd.d(477,40): Deprecation: data.ptr cannot be used in @safe code, use &data[0] instead
src/zmqd.d(567,46): Deprecation: data.ptr cannot be used in @safe code, use &data[0] instead
src/zmqd.d(582,46): Deprecation: data.ptr cannot be used in @safe code, use &data[0] instead
src/zmqd.d(624,52): Deprecation: data.ptr cannot be used in @safe code, use &data[0] instead
src/zmqd.d(636,52): Deprecation: data.ptr cannot be used in @safe code, use &data[0] instead
src/zmqd.d(1619,54): Deprecation: value.ptr cannot be used in @safe code, use &value[0] instead
src/zmqd.d(1849,9): Deprecation: items.ptr cannot be used in @safe code, use &items[0] instead
src/zmqd.d(3334,32): Deprecation: dest.ptr cannot be used in @safe code, use &dest[0] instead
src/zmqd.d(3334,42): Deprecation: data.ptr cannot be used in @safe code, use &data[0] instead
src/zmqd.d(3396,32): Deprecation: dest.ptr cannot be used in @safe code, use &dest[0] instead
src/zmqd.d(3396,42): Deprecation: text.ptr cannot be used in @safe code, use &text[0] instead
src/zmqd.d(3459,35): Deprecation: publicKeyBuf.ptr cannot be used in @safe code, use &publicKeyBuf[0] instead
src/zmqd.d(3459,53): Deprecation: secretKeyBuf.ptr cannot be used in @safe code, use &secretKeyBuf[0] instead
src/zmqd.d(3552,25): Deprecation: bytes.ptr cannot be used in @safe code, use &bytes[0] instead
src/zmqd.d(3552,50): Deprecation: text.ptr cannot be used in @safe code, use &text[0] instead
src/zmqd.d(3875,12): Deprecation: buf.ptr cannot be used in @safe code, use &buf[0] instead
```

**Comment by kyllingstad** [comment]
> If that's true, is it not error on the part of the compiler to give the below warning?

No, because you should not be trying to take the address of an empty array anyway. :-) If `a.length == 0`, then both `a.ptr` and `&a[0]` are undefined. The difference is that the error is actually handled in the latter case, because `a[0]` throws `RangeError` before it even gets to the address-taking operation.

**Comment by carun** [comment]
Oh, I see. Thanks for the details!

**Comment by wilzbach** [comment]
@kyllingstad any chance you can tag this as a new release? Otherwise it won't propagate to the project tester: https://github.com/dlang/ci/pull/121

**Comment by kyllingstad** [comment]
@wilzbach: Sure, I've tagged it with [`v1.1.1`](https://github.com/kyllingstad/zmqd/releases/tag/v1.1.1) now.

**Pull request merged**
