### PR TITLE
add Travis-CI testing

### PR DESCRIPTION
**Pull request by MartinNowak**
Automatically runs `dub test` with the latest dmd, see [Building a D Project - Travis CI](http://docs.travis-ci.com/user/languages/d/) for more info.

### CODE REVIEW

**Comment by MartinNowak** [comment]
You still need to login to travis-ci and activate this repo.

**Comment by kyllingstad** [comment]
Have you verified that this will actually work? Previous attempts have failed because Travis' version of ZeroMQ was too old.

**Comment by MartinNowak** [comment]
Ah right, I compiled+installed a recent version of zeromq and libsodium.
https://travis-ci.org/MartinNowak/zmqd/builds/81476916

**Comment by kyllingstad** [comment]
All right, thanks!

**Pull request merged**
